# Generated by Django 5.1.6 on 2025-11-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regua2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horario_estimado',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
